<#
.SYNOPSIS
    Regenerates icons/manifest.json from the SVGs present in icons/azure_V19/.

.DESCRIPTION
    Walks the icon tree, normalizes each filename into a stable identifier,
    and emits a JSON catalog the renderer reads at startup.
    Identifier rules:
      - lowercase
      - strip the leading numeric prefix Microsoft uses (e.g. "10001-icon-")
      - keep the human-readable kebab-case suffix
#>

[CmdletBinding()]
param(
    [string] $IconsDir = (Join-Path $PSScriptRoot '..\icons\azure_V19'),
    [string] $ManifestPath = (Join-Path $PSScriptRoot '..\icons\manifest.json')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$IconsDir = (Resolve-Path $IconsDir).Path
$VersionFile = Join-Path $IconsDir 'VERSION.txt'
$Version = if (Test-Path $VersionFile) { (Get-Content $VersionFile -Raw).Trim() } else { 'unknown' }

$icons = @()
Get-ChildItem $IconsDir -Recurse -Include '*.svg' | ForEach-Object {
    $relativePath = $_.FullName.Substring($IconsDir.Length).TrimStart('\','/').Replace('\','/')
    $category = ($relativePath -split '/')[0]
    if (-not $category) { $category = 'uncategorized' }

    $stem = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
    # Strip leading "NNNNN-icon-service-" -> "service-..."
    $clean = ($stem -replace '^\d+-icon-service-', '' -replace '^\d+-icon-', '').ToLowerInvariant()

    $icons += [PSCustomObject]@{
        id       = $clean
        name     = $stem
        file     = $relativePath
        category = $category.ToLowerInvariant()
    }
}

$manifest = [ordered]@{
    '$comment'    = 'Auto-generated by scripts/build-icon-manifest.ps1. Do not edit by hand.'
    version      = $Version
    generated_at = (Get-Date).ToString('o')
    icons        = $icons | Sort-Object id
}

$json = $manifest | ConvertTo-Json -Depth 8
Set-Content -Path $ManifestPath -Value $json -NoNewline
Write-Host "Wrote $($icons.Count) icons to $ManifestPath" -ForegroundColor Cyan
